#include<stdio.h>
#include<conio.h>
int main()
{
int  date,ch;

printf("ENTER DATE OF BIRTH AND THEN MONTH NO.: ");
scanf("%d %d",&date,&ch);
if (((date>=21)  && (ch==3)) || ((date<=20 ) && (ch==4 )))
printf("YOU ARE A ARIES(Aries is the first astrological \n sign in the zodiac, spanning the first 30 degrees of celestial longitude.\n Under the tropical zodiac, the Sun transits this sign mostly from March 21 to April 19 each year. \nThis time duration is exactly the first month of Solar Hejri calendar.\nThe symbol of the ram is based on the Chrysomallus,\n the flying ram that provided the Golden Fleece)\n AND YOUR BIRTHSTONE IS BLOODSTONE(The mineral aggregate heliotrope, also known as bloodstone, is a variety of jasper or chalcedony. The classic bloodstone is green jasper with red inclusions of hematite)");
if (((date>=21)  && (ch==4)) || ((date<=21 ) && (ch==5 )))
printf("YOU ARE A TAURUS(Taurus is the second astrological sign in the present zodiac.\n It spans the 30–60th degree of the zodiac.\n The Sun is in the sign of Taurus from about April 21 until about May 21 or from about May 16 to June 16. ) AND YOUR BIRTHSTONE IS SAPPHIRE(Sapphire is a gemstone, a variety of the mineral corundum, an aluminium oxide.\n It is typically blue in color, but natural fancy sapphires also occur in yellow, purple, orange, and green colors;\n partly sapphires show two or more colors.)");
if (((date>=22)  && (ch==5)) || ((date<=21 ) && (ch==6 )))
printf("YOU ARE A GEMINI(Gemini is the third astrological sign in the zodiac, originating from the constellation of Gemini.\n Under the tropical zodiac, the sun transits this sign between May 21 and June 21.\n Gemini is represented by The Twins Castor and Pollux) AND YOUR BIRTHSTONE IS AGATE(Agate is a rock consisting primarily of cryptocrystalline silica, chiefly chalcedony, alternating with microgranular quartz.\n It is characterized by its fineness of grain and variety of color)");
if (((date>=22)  && (ch==6)) || ((date<=22 ) && (ch==7 )))
printf("YOU ARE A CANCER(Cancer is the cardinal sign of the Water trigon, which is made up of Cancer, Pisces, and Scorpio.\n It is considered a negative sign, whose domicile, or ruling planet, is the Moon.\n Though some depictions of Cancer feature a lobster, the sign is most often represented by the crab, based on the Karkinos, a giant crab that harassed Heracles during his fight with the Hydra.) AND YOUR BIRTHSTONE IS EMERALD(Emerald is a gemstone and a variety of the mineral beryl colored green by trace amounts of chromium and sometimes vanadium.\n Beryl has a hardness of 7.5–8 on the Mohs scale.\n Most emeralds are highly included,\n so their toughness (resistance to breakage) is classified as generally poor.\n Emerald is a cyclosilicate.)");
if (((date>=23)  && (ch==7)) || ((date<=22 ) && (ch==8 )))
printf("YOU ARE A LEO(One of the most generous of the Zodiac, Leos make loyal and giving friends.\n They'll go out of their way to help, even when it conflicts with their own schedule.\n The Leo is a strong, confident personality who has the ability to make almost everyone comfortable.) AND YOUR BIRTHSTONE IS ONYX(Onyx is formed of bands of chalcedony in alternating colors.\n It is cryptocrystalline, consisting of fine intergrowths of the silica minerals quartz and moganite.\n Its bands are parallel to one another, as opposed to the more chaotic banding that often occurs in agates)");
if (((date>=23)  && (ch==8)) || ((date<=22 ) && (ch==9 )))
printf("YOU ARE A VIRGO(Individuals born during these dates, depending on which system of astrology they subscribe to, may be called Virgos or Virgoans.\n The symbol of the maiden is based on Astraea.\n In Greek mythology, she was the last immortal to abandon Earth at the end of the Silver Age, when the gods fled to Olympus – hence the sign's association with Earth.) AND YOUR BIRTHSTONE IS CARNELIAN(Carnelian (also spelled cornelian) is a brownish-red mineral commonly used as a semi-precious gemstone.\n Similar to carnelian is sard, which is generally harder and darker (the difference is not rigidly defined, and the two names are often used interchangeably).\n Both carnelian and sard are varieties of the silica mineral chalcedony colored by impurities of iron oxide.\n The color can vary greatly, ranging from pale orange to an intense almost-black coloration.\n It is most common in Brazil, India, Siberia and Germany.)");
if (((date>=23)  && (ch==9)) || ((date<=23 ) && (ch==10 )))
printf("YOU ARE A LIBRA( The anatomical areas for Libra are the kidneys, lower back, adrenal glands, and the appendix.\n The ruling planet for Libra is Venus.\n This planet's action is gentle and harmonious.) AND YOUR BIRTHSTONE IS CHRYSOLITE(Chrysolite is mentioned several times in the Bible, in the list of gemstones set in the breastplate of Aaron (Book of Exodus), as well as in the list of foundation stones for the New Jerusalem (in Revelation).\n Many of the gemstone references in the Bible are somewhat obscure since many gemstone names were used to refer to stones of a particular color rather than specific minerals.)");
if (((date>=24)  && (ch==10)) || ((date<=21 ) && (ch==11 )))
printf("YOU ARE A SCORPIO(The Scorpio-born are extremely mysterious individuals.\n They have strong will power and possess the capability to turn the tables around, whichever way they desire.\n Nonetheless, they have extremely distinct outer appearance.) AND YOUR BIRTHSTONE IS BERYL( beryl is colorless, but it also occurs in a variety of colors including green, yellow, greenish-yellow, blue to blue-green, red, colorless and pink when tinted by impurities.\n The pink variety is known as Morganite, red is very rare and known as Bixbite, Goshenite is the colorless form.)");
if (((date>=22)  && (ch==11)) || ((date<=21 ) && (ch==12 )))
printf("YOU ARE A SAGITTARIUS(Frank, courageous and generous, the Sagittarius-born are one of a kind.\n Most of them are prone to remain in their own worlds, deeply involved in culture, intellectual and creative pursuits, travel and even self-praise.) AND YOUR BIRTHSTONE IS TOPAZ(Topaz is found in many colors such as blue, pink, brown, green, and colorless, but yellow is the color most often associated with this gem.\n All yellow stones were once called topaz but today the real orange-red “imperial” variety is a rare find.)");
if (((date>=22)  && (ch==12)) || ((date<=21 ) && (ch==1 )))
printf("YOU ARE A CAPRICORN(The Capricorn-born people are the most determined of the entire Zodiac.\n The most prominent qualities of the Goats, as they are called, are that they are ambitious, conservative, determined, practical and helpful) AND YOUR BIRTHSTONE IS RUBY(A ruby is a pink to blood-red colored gemstone, a variety of the mineral corundum.\n Other varieties of gem-quality corundum are called sapphires.\n Ruby is one of the traditional cardinal gems, together with amethyst, sapphire, emerald, and diamond.)");
if (((date>=22)  && (ch==1)) || ((date<=18 ) && (ch==2 )))
printf("YOU ARE A AQUARIUS(Aquarius is the eleventh astrological sign in the Zodiac.Aquarius are truthfulness, just, curious, affectionate Personality, Frank and Imaginative. But they are unpredictable, detachment, tendency to go off-track, and Inefficiency.) AND YOUR BIRTHSTONE IS GARNET(Garnets are a group of silicate minerals that have been used since the Bronze Age as gemstones and abrasives. All species of garnets possess similar physical properties and crystal forms, but differ in chemical composition.)");
if (((date>=19)  && (ch==2)) || ((date<=20 ) && (ch==3 )))
printf("YOU ARE A PISCES( The Pisces or the Fish is considered as the proverbial dreamers of the Zodiac! They are lovely, mystical and compassionate beings.\n They can be the dream-lovers or partners in the positive manifestation of their personalities.) AND YOUR BIRTHSTONE IS AMETHYST(Amethyst is the birthstone for the month of February, and the official gem for Wednesday, Jupiter and those born under the sign of Pisces.\n Amethyst has been used to symbolize deep love, happiness, humility, sincerity and wealth.");
getch();
}
